# Jwt
JWT_SECRET: "SECRET JWT FOR CI DO NOT USE THIS IN PRODUCTION"
JWT_EXPIRATION_TIME: 1000

# Postgres
POSTGRES_DB: ideasmanager
POSTGRES_USER: ideasmanager
POSTGRES_PWD: ideasmanager
POSTGRES_HOST: localhost
