# Logging
LOG_LEVEL: INFO  # Not mandatory

# Jwt
JWT_SECRET: SETME
JWT_EXPIRATION_TIME: 3000000

# Postgres
POSTGRES_DB: SETME
POSTGRES_USER: SETME
POSTGRES_PWD: SETME
POSTGRES_HOST: SETME
POSTGRES_PORT: 5432  # Not mandatory
