# Jwt
JWT_SECRET: "SECRET_JWT_FOR_CI_DO_NOT_USE_IT_IN_PRODUCTION"
JWT_EXPIRATION_TIME: 1000

# Postgres
POSTGRES_DB: ideasmanager
POSTGRES_USER: ideasmanager
POSTGRES_PWD: ideasmanager
POSTGRES_HOST: localhost
