# Jwt
JWT_SECRET: "SECRETJWTFORCIDONOTUSEITINPRODUCTION"
JWT_EXPIRATION_TIME: 1000

# Postgres
POSTGRES_DB: ideasmanager
POSTGRES_USER: ideasmanager
POSTGRES_PWD: ideasmanager
POSTGRES_HOST: localhost
